c1 = input("이름을 입력하세요: ")
c2 = input("학번을 입력하세요: ")
c3 = input("학과를 입력하세요: ")
c4 = input("학교를 입력하세요: ")
print("<출력>")
print(f"이름: {c1}")
print(f"학번: {c2}")
print(f"학과: {c3}")
print(f"학교: {c4}")

print("hello world")